# Generated by Django 2.1.1 on 2018-09-19 21:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido')),
                ('email', models.EmailField(max_length=254)),
                ('num_card', models.IntegerField(verbose_name='Numero de tarjeta')),
                ('observations', models.TextField(blank=True, verbose_name='Observaciones')),
                ('check_in', models.DateField(null=True, verbose_name='Check-in')),
                ('check_out', models.DateField(null=True, verbose_name='Check-out')),
                ('total_price', models.IntegerField(default=0)),
                ('type_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.Room', verbose_name='Type of room')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reservation',
            },
        ),
    ]
